const PRODUCTS={
  postal:{name:'Postal',desc:'Recuerdo, regalo o pieza turística',fields:[['title','Título','input','Ej. Chañar, tierra de vino y chacras'],['subtitle','Frase','input','Una frase breve y poética'],['body','Texto','textarea','Historia, dato o invitación'],['source','Fuente','input','Fuente o archivo'],['credit','Crédito','input','Autor / licencia'],['image','Foto','file','']]},
  ficha:{name:'Ficha cultural',desc:'Lugar, persona, patrimonio o experiencia',fields:[['title','Nombre','input','Ej. Río Neuquén'],['category','Tipo','select','|Lugar|Persona|Patrimonio|Historia|Turismo|Cultura|Rural|Naturaleza'],['body','Texto','textarea','Información breve, humana y verificable'],['location','Dónde','input','Ubicación'],['source','Fuente','input','Fuente o archivo'],['credit','Crédito','input','Autor / licencia'],['image','Foto','file','']]},
  guide:{name:'Guía',desc:'Mini guía para descubrir Chañar',fields:[['title','Título','input','Ej. 5 postales para descubrir Chañar'],['intro','Introducción','textarea','Invitación al recorrido'],['items','Paradas','textarea','Una parada por línea'],['source','Fuentes','textarea','Fuentes utilizadas'],['image','Foto de portada','file','']]},
  infographic:{name:'Infografía',desc:'Historia, datos, calendario o identidad',fields:[['title','Título','input','Ej. Chañar en 5 postales'],['headline','Dato principal','input','Un dato fuerte y comprobado'],['body','Contenido','textarea','Datos breves, claros y visuales'],['source','Fuente','input','Fuente verificable'],['image','Foto','file','']]}
};

const TEMPLATES=[
 {id:'postal-vino',product:'postal',name:'Vino + paisaje',title:'Chañar, donde el vino encuentra la estepa',subtitle:'Viñedos, bardas y agua en el valle del río Neuquén.',body:'Una postal para descubrir la identidad vitivinícola y productiva de San Patricio del Chañar.',image:'vineyard'},
 {id:'postal-rio',product:'postal',name:'Río Neuquén',title:'El río que hizo posible el oasis',subtitle:'Agua, chacras y paisaje patagónico.',body:'El paisaje de Chañar se entiende también desde el río Neuquén y la transformación productiva del valle.',image:'river'},
 {id:'postal-chacras',product:'postal',name:'Chacras',title:'Entre álamos, frutales y viñedos',subtitle:'Una Patagonia verde nacida del riego.',body:'Una postal de la matriz rural y productiva que caracteriza al valle inferior del río Neuquén.',image:'orchards'},
 {id:'postal-patagonia',product:'postal',name:'Patagonia',title:'Chañar: tierra, viento y horizonte',subtitle:'El contraste entre la estepa y el oasis.',body:'Una imagen de identidad local para guardar, regalar o compartir.',image:'landscape'},
 {id:'ficha-vino',product:'ficha',name:'Identidad del vino',title:'San Patricio del Chañar',category:'Turismo',body:'Localidad neuquina reconocida por sus viñedos, bodegas y experiencias enoturísticas, donde el paisaje productivo se encuentra con la cultura del vino.',location:'San Patricio del Chañar, Neuquén',source:'Turismo Neuquén',image:'vineyard'},
 {id:'ficha-paisaje',product:'ficha',name:'Paisaje',title:'Valle inferior del río Neuquén',category:'Naturaleza',body:'Un paisaje de estepa, bardas, cortinas de álamos, frutales y grandes extensiones de viñedos atravesado por el río Neuquén.',location:'San Patricio del Chañar',source:'Caracterización de las regiones vitivinícolas argentinas',image:'landscape'},
 {id:'ficha-chacra',product:'ficha',name:'Chacras',title:'El oasis productivo',category:'Rural',body:'El riego transformó el valle en un mosaico de chacras, frutales y viñedos que hoy forma parte de la identidad territorial.',location:'San Patricio del Chañar',source:'Fuentes oficiales y territoriales',image:'orchards'},
 {id:'guide-postales',product:'guide',name:'5 postales',title:'Cinco maneras de mirar Chañar',intro:'Una mini guía para observar el territorio más allá de una sola imagen.',items:'El río Neuquén\nLos viñedos y bodegas\nLas chacras y frutales\nLas bardas y la estepa\nLa vida cultural y productiva del pueblo',source:'Turismo Neuquén · fuentes territoriales',image:'vineyard'},
 {id:'guide-vino',product:'guide',name:'Ruta del vino',title:'Un paseo entre viñedos',intro:'Chañar combina producción, paisaje, gastronomía y experiencias alrededor del vino.',items:'Elegí una bodega y verificá sus horarios\nRecorré los viñedos y observá el paisaje\nConocé la historia productiva del valle\nDisfrutá la gastronomía regional\nGuardá una postal del recorrido',source:'Turismo Neuquén',image:'vineyard'},
 {id:'guide-rural',product:'guide',name:'Paisaje rural',title:'Una tarde de chacras y álamos',intro:'Una propuesta tranquila para mirar el territorio con otros ojos.',items:'Observar las cortinas de álamos\nReconocer viñedos y frutales\nBuscar el contraste entre oasis y estepa\nRegistrar colores y texturas\nCerrar el recorrido junto al paisaje del río',source:'Fuentes territoriales',image:'orchards'},
 {id:'info-identidad',product:'infographic',name:'Identidad',title:'Chañar en 5 ideas',headline:'VINO · RÍO · CHACRAS · ESTEPA · HISTORIA',body:'Una identidad territorial construida entre el agua, la producción, el paisaje patagónico y las historias de quienes habitan el valle.',source:'Turismo Neuquén · fuentes territoriales',image:'landscape'},
 {id:'info-paisaje',product:'infographic',name:'Paisaje',title:'El paisaje de Chañar',headline:'OASIS + ESTEPA',body:'El valle combina viñedos y frutales irrigados con bardas, estepa patagónica, cortinas forestales y visuales amplias.',source:'Caracterización de las regiones vitivinícolas argentinas',image:'vineyard'}
];

const PHOTO_BANK=[
 {id:'vineyard',name:'Viñedos y estepa',url:'https://www.rionegro.com.ar/sociedad/voy-turismo/san-patricio-del-chanar-celebra-su-aniversario-consolidado-como-capital-del-vino-y-protagonista-de-una-vendimia-historica/'},
 {id:'river',name:'Río Neuquén / paisaje',url:'https://cfi.org.ar/uploads/2024/05/Neuquen_114_0.pdf'},
 {id:'orchards',name:'Chacras y paisaje productivo',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
 {id:'landscape',name:'Paisaje vitivinícola',url:'https://publications.iadb.org/publications/spanish/document/Caracterizacion-de-las-regiones-vitivinicolas-argentinas.pdf'},
 {id:'town',name:'San Patricio del Chañar',url:'https://commons.wikimedia.org/wiki/Category:San_Patricio_del_Chañar'},
 {id:'wineries',name:'Bodegas',url:'https://turismo.neuquen.gob.ar/que-hacer-donde-vive-el-vino/'},
 {id:'harvest',name:'Vendimia',url:'https://www.lmneuquen.com/neuquen/en-17-fotos-la-vendimia-neuquina-se-lucio-bodega-malma-n1231663'},
 {id:'schroeder',name:'Familia Schroeder',url:'https://www.argentina.travel/enoturismo/familia-schroeder'},
 {id:'wine-road',name:'Camino del Vino',url:'https://www.neuqueninforma.gob.ar/noticias/2025/03/17/248420-relevaron-el-trazado-del-proyecto-del-camino-del-vino'},
 {id:'culture',name:'Cultura y turismo',url:'https://www.neuqueninforma.gob.ar/noticias/2026/04/03/255930-el-chical-se-suma-a-la-oferta-vitivinicola-de-san-patricio-del-chanar'}
];

const PHOTO_URLS={
 vineyard:'https://images.unsplash.com/photo-1473973266408-ed4e27abdd47?auto=format&fit=crop&w=1400&q=85',
 river:'https://images.unsplash.com/photo-1437482078695-73f5ca6c96e2?auto=format&fit=crop&w=1400&q=85',
 orchards:'https://images.unsplash.com/photo-1464638681273-09681d4b1f7a?auto=format&fit=crop&w=1400&q=85',
 landscape:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85'
};

const KEY='fabrica-chanar-simple-v1';const $=s=>document.querySelector(s);const clean=v=>typeof v==='string'?v.trim():'';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let state={type:'postal',data:{},image:null};
function library(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function setLibrary(x){localStorage.setItem(KEY,JSON.stringify(x.slice(0,100)));updateLibraryCount()}
function updateLibraryCount(){$('#libraryCount').textContent=library().length}
function setStatus(x){$('#status').textContent=x||''}
function renderProducts(){$('#productGrid').innerHTML=Object.entries(PRODUCTS).map(([id,p])=>`<button type="button" class="product-btn ${id===state.type?'active':''}" data-product="${id}"><strong>${p.name}</strong><small>${p.desc}</small></button>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{state={type:b.dataset.product,data:{},image:null};renderProducts();renderForm();renderPreview();setStatus('Elegí una plantilla o completá la pieza.');renderTemplates()})}
function renderTemplates(){const list=TEMPLATES.filter(x=>x.product===state.type);$('#templateGrid').innerHTML=list.map(x=>`<button class="template-card" data-template="${x.id}"><span class="template-art ${x.image||''}"></span><strong>${esc(x.name)}</strong><small>Usar esta plantilla</small></button>`).join('');document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>useTemplate(b.dataset.template));}
function useTemplate(id){const t=TEMPLATES.find(x=>x.id===id);if(!t)return;state.data={...t};delete state.data.id;delete state.data.product;delete state.data.name;const bank=PHOTO_BANK.find(x=>x.id===t.image);if(PHOTO_URLS[t.image])state.image=PHOTO_URLS[t.image];renderForm();renderPreview();setStatus(`Plantilla “${t.name}” cargada. Podés descargarla o retocarla.`)}
function renderPhotoBank(){$('#photoBank').innerHTML=PHOTO_BANK.map(x=>`<a class="photo-source" href="${x.url}" target="_blank" rel="noopener"><span class="photo-thumb ${x.id}"></span><strong>${esc(x.name)}</strong><small>ver fuente</small></a>`).join('')}
function renderForm(){const p=PRODUCTS[state.type];$('#editorForm').innerHTML=p.fields.map(([key,label,kind,ph])=>{if(kind==='file')return `<div class="field"><label>${label}</label><input id="field-${key}" type="file" accept="image/*"><div class="hint">También podés usar una foto propia.</div></div>`;if(kind==='select')return `<div class="field"><label>${label}</label><select id="field-${key}">${ph.split('|').map((x,i)=>`<option value="${esc(x)}" ${i===0?'selected':''}>${esc(x||'Elegir...')}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}</label>${kind==='textarea'?`<textarea id="field-${key}" placeholder="${esc(ph)}"></textarea>`:`<input id="field-${key}" placeholder="${esc(ph)}">`}</div>`}).join('');$('#editorForm').querySelectorAll('input:not([type=file]),textarea,select').forEach(el=>{const k=el.id.replace('field-','');el.value=state.data[k]??'';el.oninput=()=>{state.data[k]=el.value;renderPreview()}});const file=$('#field-image');if(file)file.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.image=r.result;renderPreview()};r.readAsDataURL(f)}}
function bodyHTML(){const d=state.data;if(state.type==='guide')return `<ul>${(d.items||'').split(/\r?\n/).filter(clean).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;return `<p>${esc(d.body||d.intro||d.headline||'Elegí una plantilla para comenzar.')}</p>`}
function renderPreview(){const d=state.data;const image=state.image?`<img src="${esc(state.image)}" alt="">`:'';const category=state.type==='ficha'&&d.category?`<div class="piece-meta">${esc(d.category)}${d.location?` · ${esc(d.location)}`:''}</div>`:'';$('#canvasPreview').innerHTML=`<article class="piece ${state.type}"><div class="piece-image">${image}<div class="image-overlay"></div></div><div class="piece-content"><div class="piece-kicker">OCARINA · SAN PATRICIO DEL CHAÑAR</div><h3>${esc(d.title||'Tu postal comienza acá')}</h3>${d.subtitle?`<div class="piece-subtitle">${esc(d.subtitle)}</div>`:''}${d.headline?`<div class="piece-headline">${esc(d.headline)}</div>`:''}${category}${bodyHTML()}${d.source?`<div class="piece-source">Fuente: ${esc(d.source)}</div>`:''}${d.credit?`<div class="piece-credit">Imagen: ${esc(d.credit)}</div>`:''}<div class="piece-brand">Fábrica Chañar · Historias, personas y territorio</div></div></article>`}
function validate(){const d=state.data;if(!clean(d.title)){setStatus('Elegí una plantilla o escribí un título.');return false}const t=state.type==='guide'?clean(d.intro)||clean(d.items):clean(d.body)||clean(d.headline);if(!t){setStatus('Falta contenido.');return false}return true}
function save(){if(!validate())return;setLibrary([{id:'pieza-'+Date.now(),type:state.type,data:{...state.data},image:state.image,created:new Date().toISOString()},...library()]);setStatus('Guardada en la biblioteca.')}
function openLibrary(){const a=library();$('#libraryList').innerHTML=a.length?a.map(x=>`<div class="library-card"><div><strong>${esc(x.data?.title||PRODUCTS[x.type]?.name)}</strong><small>${esc(PRODUCTS[x.type]?.name||x.type)} · ${new Date(x.created).toLocaleDateString('es-AR')}</small></div><div class="library-buttons"><button data-open="${x.id}">Abrir</button><button data-delete="${x.id}">Eliminar</button></div></div>`).join(''):'<p class="empty">Todavía no guardaste piezas.</p>';$('#libraryPanel').classList.remove('hidden');$('#libraryList').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const x=library().find(y=>y.id===b.dataset.open);if(!x)return;state={type:x.type,data:x.data||{},image:x.image||null};renderProducts();renderTemplates();renderForm();renderPreview();$('#libraryPanel').classList.add('hidden')});$('#libraryList').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{setLibrary(library().filter(x=>x.id!==b.dataset.delete));openLibrary()})}
async function exportImage(kind){if(!validate())return;if(typeof html2canvas!=='function'){setStatus('El motor gráfico no está disponible.');return}const c=await html2canvas($('#canvasPreview'),{scale:2,useCORS:true,backgroundColor:'#f4efe3'});const a=document.createElement('a');a.download=`fabrica-chanar-${Date.now()}.${kind}`;a.href=c.toDataURL(kind==='jpg'?'image/jpeg':'image/png',.94);a.click();setStatus(`Descargada en ${kind.toUpperCase()}.`)}
$('#btnGenerate').onclick=()=>{if(validate()){renderPreview();setStatus('Lista para descargar.')}};$('#btnSave').onclick=save;$('#btnPng').onclick=()=>exportImage('png');$('#btnJpg').onclick=()=>exportImage('jpg');$('#btnPrint').onclick=()=>{if(validate())window.print()};$('#btnLibrary').onclick=openLibrary;$('#btnCloseLibrary').onclick=()=>$('#libraryPanel').classList.add('hidden');
renderProducts();renderTemplates();renderPhotoBank();renderForm();renderPreview();updateLibraryCount();