const PRODUCTS={
 postal:{name:'Postal',desc:'Historia, territorio o turismo',fields:[['title','Título','input','Ej. Un lugar del Chañar'],['subtitle','Bajada','input','Una frase breve'],['body','Texto','textarea','Descripción verificable'],['source','Fuente','input','Institución, archivo, publicación o enlace'],['credit','Crédito de imagen','input','Autor / archivo / propia'],['image','Imagen','file','']]},
 ficha:{name:'Ficha local',desc:'Lugar, persona, hecho o patrimonio',fields:[['title','Nombre de la ficha','input','Ej. lugar / persona / institución'],['category','Categoría','select','Lugar|Persona|Institución|Comercio|Patrimonio|Historia|Turismo|Cultura|Rural|Producción|Servicios|Naturaleza'],['body','Descripción','textarea','Información breve y verificable'],['location','Ubicación','input','Solo si está verificada'],['source','Fuente','input','Fuente de la información'],['image','Imagen','file','']]},
 guide:{name:'Guía',desc:'Información práctica ordenada',fields:[['title','Título','input','Ej. Guía del territorio'],['intro','Introducción','textarea','Qué encontrará el lector'],['items','Contenido','textarea','Un punto por línea'],['source','Fuentes','textarea','Fuentes utilizadas'],['image','Imagen de portada','file','']]},
 infographic:{name:'Archivo útil',desc:'Infografía, calendario, directorio o educativo',fields:[['title','Título','input','Tema del archivo'],['headline','Dato principal','input','Solo un dato comprobado'],['body','Contenido','textarea','Información y aclaraciones'],['source','Fuente','input','Fuente verificable'],['image','Imagen','file','']]},
 map:{name:'Mapa',desc:'Referencias territoriales',fields:[['title','Título','input','Ej. San Patricio del Chañar'],['body','Referencias','textarea','Una referencia por línea'],['source','Fuente cartográfica','input','Fuente / fecha'],['note','Nota cartográfica','textarea','Aclaraciones y limitaciones'],['image','Imagen de fondo opcional','file','']]}
};
const TEMPLATES={postal:[['P01','Paisaje'],['P02','Historia'],['P03','Turismo'],['P04','Persona'],['P05','Efeméride']],map:[['M01','General'],['M02','Turismo'],['M03','Histórico'],['M04','Cultural'],['M05','Rural']],ficha:[['F01','Lugar'],['F02','Persona'],['F03','Institución'],['F04','Comercio'],['F05','Patrimonio']],guide:[['G01','Turismo'],['G02','Historia'],['G03','Cultura'],['G04','Paseo'],['G05','Familia']],infographic:[['A01','Calendario'],['A02','Directorio'],['A03','Cronología'],['A04','Infografía'],['A05','Documento educativo']]};
let state={type:'postal',template:'P01',data:{},image:null};
const $=s=>document.querySelector(s);
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function renderProducts(){const el=$('#productGrid');el.innerHTML=Object.entries(PRODUCTS).map(([id,p])=>`<button type="button" class="product-btn ${id===state.type?'active':''}" data-product="${id}"><strong>${p.name}</strong><small>${p.desc}</small></button>`).join('');el.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{state={type:b.dataset.product,template:TEMPLATES[b.dataset.product]?.[0]?.[0]||'',data:{},image:null};renderAll();});}
function renderForm(){const form=$('#editorForm'),templates=TEMPLATES[state.type]||[];form.innerHTML=(templates.length?`<div class="field"><label for="field-template">Plantilla</label><select id="field-template">${templates.map(([id,name])=>`<option value="${id}" ${id===state.template?'selected':''}>${id} — ${name}</option>`).join('')}</select><div class="hint">La plantilla define la estructura visual; los datos siguen siendo documentables.</div></div>`:'')+PRODUCTS[state.type].fields.map(([key,label,kind,placeholder])=>{if(kind==='file')return `<div class="field"><label for="field-${key}">${label}</label><input class="image-input" id="field-${key}" type="file" accept="image/*"><div class="hint">La imagen queda en este navegador; no se sube a un servidor.</div></div>`;if(kind==='select')return `<div class="field"><label for="field-${key}">${label}</label><select id="field-${key}">${placeholder.split('|').map(x=>`<option>${x}</option>`).join('')}</select></div>`;return `<div class="field"><label for="field-${key}">${label}</label>${kind==='textarea'?`<textarea id="field-${key}" placeholder="${escapeHTML(placeholder)}"></textarea>`:`<input id="field-${key}" placeholder="${escapeHTML(placeholder)}">`}</div>`}).join('');
form.querySelectorAll('input:not([type=file]),textarea,select').forEach(i=>{const k=i.id.replace('field-','');i.value=state.data[k]??(k==='template'?state.template:'');i.addEventListener('input',()=>{if(k==='template')state.template=i.value;else state.data[k]=i.value;renderPreview();updateSource();});});const file=$('#field-image');if(file)file.addEventListener('change',handleImage);}
function handleImage(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.image=r.result;renderPreview();};r.readAsDataURL(f);}
function sourceState(data=state.data){return Object.values(data).some(v=>typeof v==='string'&&v.trim()&&/fuente|source/i.test(''))? 'declarada':(data.source?.trim()?'declarada':'pendiente');}
function renderPreview(){const d=state.data;let body='';if(state.type==='guide')body=(d.items||'').split('\n').filter(Boolean).map(x=>`<li>${escapeHTML(x)}</li>`).join('');else if(state.type==='map')body=`<div class="mapbox"><div class="schematic-label">MAPA ESQUEMÁTICO · NO NAVEGACIÓN</div><div class="north">N</div><div class="road r1"></div><div class="road r2"></div><div class="river"></div>${(d.body||'').split('\n').filter(Boolean).slice(0,8).map((x,i)=>`<span class="pin p${i}">${i+1}</span>`).join('')}</div>`;else body=`<p>${escapeHTML(d.body||d.intro||d.headline||'Completá el contenido para comenzar.')}</p>`;const image=state.image?`<img src="${state.image}" alt="Fotografía de la pieza">`:'';const source=d.source?`Fuente declarada: ${escapeHTML(d.source)}`:'Fuente pendiente de completar';$('#canvasPreview').innerHTML=`<article class="piece ${state.type} template-${escapeHTML(state.template)}"><div class="piece-image">${image}</div><div class="piece-content"><div class="piece-kicker">SAN PATRICIO DEL CHAÑAR · ${escapeHTML(state.template||'SIN PLANTILLA')}</div><h3>${escapeHTML(d.title||'Título de la pieza')}</h3>${d.subtitle?`<div class="piece-subtitle">${escapeHTML(d.subtitle)}</div>`:''}${state.type==='guide'?`<ul>${body}</ul>`:body}${d.location?`<div class="piece-meta">Ubicación: ${escapeHTML(d.location)}</div>`:''}${d.note?`<div class="piece-note">${escapeHTML(d.note)}</div>`:''}<div class="piece-source">${source}</div><div class="piece-brand">Fábrica Chañar · una herramienta de Ocarina Producciones</div></div></article>`;}
function updateSource(){const ok=sourceState()==='declarada';$('#sourceStatus').textContent=ok?'Fuente declarada. Verificá que corresponda exactamente al dato utilizado.':'Fuente pendiente: esta pieza no debe presentarse como documentada.';$('#sourceStatus').className=ok?'source-ok':'source-pending';}
function getLibrary(){try{return JSON.parse(localStorage.getItem('fabrica-chanar-library')||'[]')}catch{return[]}}
function saveItem(item){const arr=getLibrary();arr.unshift(item);localStorage.setItem('fabrica-chanar-library',JSON.stringify(arr.slice(0,100)));}
function save(){saveItem({id:Date.now(),type:state.type,template:state.template,data:{...state.data},image:state.image,created:new Date().toISOString(),batch:false});renderLibrary();$('#libraryPanel').classList.remove('hidden');}
function renderLibrary(){const arr=getLibrary();$('#libraryCount').textContent=arr.length;const el=$('#libraryList');el.innerHTML=arr.length?arr.map(x=>`<div class="library-card"><strong>${escapeHTML(x.data.title||PRODUCTS[x.type]?.name||'Pieza')}</strong><p>${PRODUCTS[x.type]?.name||x.type} · ${escapeHTML(x.template||'')} · ${new Date(x.created).toLocaleDateString('es-AR')}</p><button data-load="${x.id}">Abrir</button></div>`).join(''):'<p>Tu biblioteca está vacía. Guardá una pieza para verla acá.</p>';el.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const x=arr.find(y=>y.id==b.dataset.load);if(x){state={type:x.type,template:x.template||TEMPLATES[x.type]?.[0]?.[0]||'',data:x.data||{},image:x.image||null};renderAll();$('#libraryPanel').classList.add('hidden');}});}
function makeVariant(type){const d=state.data;const base={title:d.title||'Sin título',source:d.source||'',image:state.image};if(type==='postal')return {...base,subtitle:d.subtitle||'',body:d.body||d.intro||d.headline||''};if(type==='ficha')return {...base,category:d.category||'Lugar',body:d.body||d.intro||d.headline||'',location:d.location||''};if(type==='guide')return {...base,intro:d.body||d.intro||d.headline||'',items:(d.body||d.items||'').split('\n').filter(Boolean).join('\n'),source:d.source||''};return {...base,headline:d.headline||d.title||'',body:d.body||d.intro||'',source:d.source||''};}
function generateBatch(){const selected=[...document.querySelectorAll('.batch-grid input:checked')].map(x=>x.value);if(!selected.length){$('#batchStatus').textContent='Elegí al menos un formato.';return}const original={...state};let created=0;selected.forEach(type=>{const item={id:Date.now()+created,type,template:TEMPLATES[type]?.[0]?.[0]||'',data:makeVariant(type),image:state.image,created:new Date().toISOString(),batch:true,sourceType:state.type};saveItem(item);created++;});renderLibrary();$('#batchStatus').textContent=`Colección creada: ${created} piezas guardadas en la biblioteca.`;state=original;}
async function exportImage(kind){if(typeof html2canvas!=='function'){alert('No se pudo cargar el motor de exportación. Revisá tu conexión y probá nuevamente.');return}const node=$('#canvasPreview'),c=await html2canvas(node,{scale:2,useCORS:true,backgroundColor:null});const a=document.createElement('a');a.download=`fabrica-chanar-${Date.now()}.${kind}`;a.href=c.toDataURL(kind==='jpg'?'image/jpeg':'image/png',.94);a.click();}
function share(){const payload={type:state.type,template:state.template,data:state.data};const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(payload))));location.hash='pieza='+encoded;updateShareButton();}
function loadShare(){if(!location.hash.startsWith('#pieza='))return;try{const raw=decodeURIComponent(escape(atob(location.hash.slice(7)))),x=JSON.parse(raw);if(!PRODUCTS[x.type])return;state={type:x.type,template:x.template||TEMPLATES[x.type]?.[0]?.[0]||'',data:x.data||{},image:null};renderAll();}catch{}}
function updateShareButton(){const b=$('#btnShare');if(b)b.textContent=location.hash?'Enlace actualizado':'Compartir pieza';}
function renderAll(){renderProducts();renderForm();renderPreview();updateSource();updateShareButton();}
$('#btnPng').onclick=()=>exportImage('png');$('#btnJpg').onclick=()=>exportImage('jpg');$('#btnPrint').onclick=()=>window.print();$('#btnGenerate').onclick=renderPreview;$('#btnSave').onclick=save;$('#btnShare').onclick=share;$('#btnBatch').onclick=generateBatch;$('#btnLibrary').onclick=()=>{$('#libraryPanel').classList.toggle('hidden');renderLibrary()};$('#btnCloseLibrary').onclick=()=>$('#libraryPanel').classList.add('hidden');$('#btnNew').onclick=()=>{history.replaceState(null,'',location.pathname+location.search);state={type:'postal',template:'P01',data:{},image:null};renderAll();};
renderAll();renderLibrary();loadShare();