const PHOTO_BANK=[
 {id:'ingreso',name:'Ingreso a San Patricio del Chañar',photo:'https://upload.wikimedia.org/wikipedia/commons/7/7c/San_Patricio_del_Chañar.png',source:'Wikimedia Commons · CC BY 3.0',url:'https://commons.wikimedia.org/wiki/File:San_Patricio_del_Chañar.png',kind:'usable'},
 {id:'malma1',name:'Bodega Malma · acceso y viñedos',photo:'https://cdn3.neuqueninforma.com.ar/s3i233/2026/04/neuqueninforma/images/02/53/48/2534897_44c7a411b0610cee0f3caadf94c192c0659b7cf906b8fd348ff333c167d8386d/md.webp',source:'Neuquén Informa · Bodega Malma',url:'https://www.neuqueninforma.gob.ar/noticias/2026/04/01/255926-cierre-de-lujo-para-el-ciclo-sunsets-en-san-patricio-del-chanar',kind:'reference'},
 {id:'malma2',name:'Bodega Malma · viñedos',photo:'https://cdn3.neuqueninforma.com.ar/s3i233/2026/03/neuqueninforma/images/02/50/79/2507944_37f1255f9cb90154c0a7d5bb0ee381ec1562e2a9766060cdde64c25847cff399/md.webp',source:'Neuquén Informa · Vendimia 2026',url:'https://www.neuqueninforma.gob.ar/noticias/2026/03/12/255578-vinos-musica-sinfonica-djs-y-arte-en-bodega-malma',kind:'reference'},
 {id:'schroeder',name:'Bodega Familia Schroeder · cava',photo:'https://cdn3.neuqueninforma.com.ar/s3i233/2026/05/neuqueninforma/images/02/60/80/2608075_b6e8c378041672dbf2677b9ee78c9439bb3d94f327daf9b4dbfc075026972466/md.webp',source:'Neuquén Informa · Familia Schroeder',url:'https://www.neuqueninforma.gob.ar/noticias/2026/05/23/258207-bodega-familia-schroeder-celebra-con-una-propuesta-de-enoturismo-sabores-patrios-y-musica-en-vivo',kind:'reference'},
 {id:'vendimia1',name:'Vendimia · Bodega Familia Schroeder',photo:'https://media.lmneuquen.com/p/a2f924baa6348644ddf491cccc557daf/adjuntos/195/imagenes/007/862/0007862762/770x0/smart/vendimia-neuquina-bodega-familia-schroeder-2jpg.jpg',source:'LM Neuquén · Vendimia 2025',url:'https://www.lmneuquen.com/neuquen/san-patricio-del-chanar-celebro-el-exito-la-vendimia-neuquina-2025-n1180085',kind:'reference'},
 {id:'vendimia2',name:'Vendimia · paisaje de bodega',photo:'https://media.lmcipolletti.com/p/7430df314d0a690a568dea239cc2598b/adjuntos/195/imagenes/007/862/0007862747/1170x658/smart/vendimia-neuquina-bodega-familia-schroeder-10jpg.jpg',source:'LM Cipolletti · Vendimia 2025',url:'https://www.lmneuquen.com/neuquen/san-patricio-del-chanar-celebro-el-exito-la-vendimia-neuquina-2025-n1180085',kind:'reference'},
 {id:'malma3',name:'Vendimia · Bodega Familia Schroeder',photo:'https://media.lmcipolletti.com/p/b72988b7dce9b3c84ff2df3945645c8b/adjuntos/195/imagenes/007/862/0007862753/1170x658/smart/vendimia-neuquina-bodega-familia-schroeder-16jpg.jpg',source:'LM Cipolletti · Vendimia 2025',url:'https://www.lmneuquen.com/neuquen/san-patricio-del-chanar-celebro-el-exito-la-vendimia-neuquina-2025-n1180085',kind:'reference'},
 {id:'pelon',name:'Fiesta Provincial del Pelón 2026',photo:'https://cdn3.neuqueninforma.com.ar/s3i233/2026/02/neuqueninforma/images/02/46/85/2468533_ca0d33fe34eccb73798b3e345507cbe5e948e43ad493d13687c77b8d5d056647/md.webp',source:'Neuquén Informa · Fiesta del Pelón',url:'https://www.neuqueninforma.gob.ar/noticias/2026/02/10/255111-san-patricio-del-chanar-se-prepara-para-la-fiesta-del-pelon',kind:'reference'},
 {id:'patritti',name:'Bodega Patritti · interior',photo:'https://cdn3.neuqueninforma.com.ar/s3i233/2025/05/neuqueninforma/images/01/90/01/1900116_ac7cdd2a248ad971ee0239f6b670059b164f7441f18de0245255d25238462f8f/md.webp',source:'Neuquén Informa · Bodega Patritti',url:'https://www.neuqueninforma.gob.ar/noticias/2025/06/01/249561-patritti-el-renacer-de-una-bodega-en-san-patricio-del-chanar',kind:'reference'},
 {id:'chical',name:'Bodega El Chical · espacio local',photo:'https://cdn3.neuqueninforma.com.ar/s3i233/2026/04/neuqueninforma/images/02/53/49/2534972_19d21c6907d942f3c8e5e59f2356ba7d32b586f1cd4f9b692394beb92839893f/md.webp',source:'Neuquén Informa · El Chical',url:'https://www.neuqueninforma.gob.ar/noticias/2026/04/03/255930-el-chical-se-suma-a-la-oferta-vitivinicola-de-san-patricio-del-chanar',kind:'reference'}
];
const PRODUCTS={postal:{name:'Postal',desc:'Regalo, recuerdo o pieza turística'},ficha:{name:'Ficha cultural',desc:'Lugar, patrimonio, historia o experiencia'},guide:{name:'Guía breve',desc:'Recorrido listo para compartir'},infographic:{name:'Infografía',desc:'Dato, identidad, calendario o territorio'}};
const TEMPLATES=[
{id:'p-ingreso',product:'postal',style:'patagonia',name:'La puerta del Chañar',title:'San Patricio del Chañar',subtitle:'Una puerta al valle, al vino y a las historias del territorio.',body:'Postal de identidad local para guardar, regalar o compartir.',photo:'ingreso',source:'Wikimedia Commons · CC BY 3.0'},
{id:'p-vinedos',product:'postal',style:'vino',name:'Viñedos y estepa',title:'Donde el vino encuentra la estepa',subtitle:'Viñedos, paisaje patagónico y agua de riego.',body:'San Patricio del Chañar convirtió parte del valle en un paisaje vitivinícola reconocido por sus bodegas y experiencias de enoturismo.',photo:'malma2',source:'Turismo Neuquén / Neuquén Informa'},
{id:'p-cava',product:'postal',style:'cava',name:'La arquitectura del vino',title:'Entre barricas y viñedos',subtitle:'Una mirada hacia adentro del mundo del vino chañarense.',body:'La cultura vitivinícola también vive en las bodegas, sus espacios, sus recorridos y las historias de quienes producen.',photo:'schroeder',source:'Neuquén Informa'},
{id:'p-vendimia',product:'postal',style:'vendimia',name:'Vendimia',title:'Tiempo de cosecha',subtitle:'El paisaje se llena de uvas, música y encuentro.',body:'La Vendimia Neuquina reúne producción, gastronomía, cultura y turismo en las bodegas de San Patricio del Chañar.',photo:'vendimia1',source:'LM Neuquén'},
{id:'p-pelon',product:'postal',style:'fiesta',name:'Fiesta del Pelón',title:'Pelón, fiesta y raíces',subtitle:'Una celebración de la producción y la vida rural.',body:'La Fiesta Provincial del Pelón pone en escena las raíces productivas, culturales y rurales de San Patricio del Chañar.',photo:'pelon',source:'Neuquén Informa'},
{id:'p-chical',product:'postal',style:'arte',name:'El Chical',title:'El vino como excusa',subtitle:'Vino, cultura, comunidad y nuevas historias.',body:'El Chical nació en San Patricio del Chañar como bodega boutique y espacio cultural vinculado al turismo del vino.',photo:'chical',source:'Neuquén Informa'},
{id:'f-mal',product:'ficha',style:'vino',name:'Bodega Malma',title:'Bodega Malma',category:'Turismo',body:'Bodega ubicada en San Patricio del Chañar, integrada al circuito vitivinícola y a experiencias de enoturismo, gastronomía y paisaje.',location:'Ruta Provincial 7 y calle 15',photo:'malma1',source:'Turismo Neuquén / Municipalidad'},
{id:'f-sch',product:'ficha',style:'cava',name:'Familia Schroeder',title:'Bodega Familia Schroeder',category:'Turismo',body:'Una de las bodegas emblemáticas de San Patricio del Chañar, con visitas, gastronomía y un fuerte vínculo entre vino, paisaje y experiencias.',location:'Calle 7 Norte',photo:'schroeder',source:'Turismo Neuquén'},
{id:'f-pat',product:'ficha',style:'cava',name:'Patritti',title:'Bodega Patritti',category:'Producción',body:'Proyecto vitivinícola boutique que retomó la marca Patritti en San Patricio del Chañar, con nuevas hectáreas implantadas y variedades como Merlot, Chardonnay y Pinot Noir.',location:'San Patricio del Chañar',photo:'patritti',source:'Neuquén Informa'},
{id:'f-chical',product:'ficha',style:'arte',name:'El Chical',title:'Bodega El Chical',category:'Cultura',body:'Bodega urbana que propone vino, aperitivos y un espacio cultural con actividades musicales y turísticas.',location:'San Patricio del Chañar',photo:'chical',source:'Neuquén Informa'},
{id:'g-vino',product:'guide',style:'vino',name:'Paseo del vino',title:'Un día entre viñedos',intro:'Una guía breve para descubrir la identidad vitivinícola de San Patricio del Chañar.',items:'Elegí una bodega y verificá horarios y reservas\nRecorré viñedos y observá el contraste con la estepa\nConocé una propuesta gastronómica local\nEscuchá la historia de la bodega que visitás\nGuardá una postal del paisaje',photo:'malma2',source:'Turismo Neuquén'},
{id:'g-fiesta',product:'guide',style:'fiesta',name:'Fiestas y raíces',title:'Chañar de fiesta',intro:'Una pequeña guía de expresiones culturales y productivas de la localidad.',items:'Fiesta Provincial del Pelón\nVendimia Neuquina\nFerias de artesanos y emprendedores\nGastronomía regional\nMúsica, danzas y encuentros comunitarios',photo:'pelon',source:'Neuquén Informa'},
{id:'g-bodegas',product:'guide',style:'cava',name:'Bodegas',title:'Cuatro puertas al vino',intro:'Una selección visual de espacios vitivinícolas vinculados a San Patricio del Chañar.',items:'Bodega Malma\nBodega Familia Schroeder\nBodega Patritti\nBodega El Chical',photo:'schroeder',source:'Turismo Neuquén · fuentes oficiales'},
{id:'g-identidad',product:'guide',style:'patagonia',name:'Identidad',title:'Mirar Chañar',intro:'Una guía para leer el territorio con otros ojos.',items:'Río y riego\nChacras y frutales\nViñedos y bodegas\nEstepa y bardas\nFiestas, trabajo y comunidad',photo:'ingreso',source:'Fuentes oficiales territoriales'},
{id:'i-identidad',product:'infographic',style:'patagonia',name:'5 claves',title:'San Patricio del Chañar en 5 claves',headline:'RÍO · CHACRAS · VINO · FIESTAS · TERRITORIO',body:'El carácter local se construye entre el agua que permite el oasis, la producción frutícola y vitivinícola, el paisaje de estepa y las expresiones culturales de la comunidad.',photo:'ingreso',source:'Fuentes oficiales territoriales'},
{id:'i-vino',product:'infographic',style:'vino',name:'Ruta del vino',title:'Chañar, territorio del vino',headline:'VIÑEDOS + BODEGAS + PAISAJE',body:'San Patricio del Chañar forma parte del principal circuito vitivinícola neuquino. El enoturismo integra producción, gastronomía, cultura y paisaje.',photo:'malma2',source:'Turismo Neuquén'},
{id:'i-pelon',product:'infographic',style:'fiesta',name:'Pelón',title:'La Fiesta Provincial del Pelón',headline:'PRODUCCIÓN + CULTURA + CAMPO',body:'La fiesta recupera y celebra las raíces productivas y rurales de San Patricio del Chañar, con música, danzas, gastronomía, artesanos y destrezas criollas.',photo:'pelon',source:'Neuquén Informa'},
{id:'i-chical',product:'infographic',style:'arte',name:'Nueva identidad',title:'El vino también es cultura',headline:'EL CHICAL · VINO + COMUNIDAD',body:'La nueva bodega urbana El Chical plantea el vino como excusa para crear un espacio cultural, turístico y comunitario en San Patricio del Chañar.',photo:'chical',source:'Neuquén Informa'}
];
const KEY='fabrica-chanar-simple-v2';const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const clean=v=>typeof v==='string'?v.trim():'';let state={type:'postal',data:{},image:null,photoId:null};
function library(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}function setLibrary(x){localStorage.setItem(KEY,JSON.stringify(x.slice(0,100)));updateLibraryCount()}function updateLibraryCount(){$('#libraryCount').textContent=library().length}function status(x){$('#status').textContent=x||''}
function renderProducts(){$('#productGrid').innerHTML=Object.entries(PRODUCTS).map(([id,p])=>`<button type="button" class="product-btn ${id===state.type?'active':''}" data-product="${id}"><strong>${p.name}</strong><small>${p.desc}</small></button>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{state={type:b.dataset.product,data:{},image:null,photoId:null};renderProducts();renderTemplates();renderForm();renderPreview();status('Elegí una plantilla.')})}
function renderTemplates(){const list=TEMPLATES.filter(t=>t.product===state.type);$('#templateGrid').innerHTML=list.map(t=>{const p=PHOTO_BANK.find(x=>x.id===t.photo);return `<button type="button" class="template-card style-${t.style}" data-template="${t.id}"><span class="template-art"><img src="${p?.photo||''}" alt=""><i>${p?.kind==='usable'?'CC':'LOCAL'}</i></span><strong>${esc(t.name)}</strong><small>Usar plantilla</small></button>`}).join('');document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>useTemplate(b.dataset.template))}
function useTemplate(id){const t=TEMPLATES.find(x=>x.id===id);if(!t)return;state.data={title:t.title,subtitle:t.subtitle||'',body:t.body||'',category:t.category||'',location:t.location||'',source:t.source||'',headline:t.headline||'',intro:t.intro||'',items:t.items||''};state.photoId=t.photo;state.image=PHOTO_BANK.find(x=>x.id===t.photo)?.photo||null;renderForm();renderPreview();status(`“${t.name}” lista para descargar.`)}
function renderPhotoBank(){$('#photoBank').innerHTML=PHOTO_BANK.map(p=>`<a class="photo-source" href="${p.url}" target="_blank" rel="noopener"><span class="photo-thumb"><img src="${p.photo}" alt=""></span><strong>${esc(p.name)}</strong><small>${p.kind==='usable'?'CC · usar con atribución':'Referencia pública · verificar derechos'}</small></a>`).join('')}
function renderForm(){const fields=state.type==='postal'?[['title','Título'],['subtitle','Frase'],['body','Texto']]:state.type==='ficha'?[['title','Nombre'],['category','Tipo'],['body','Texto'],['location','Dónde']]:state.type==='guide'?[['title','Título'],['intro','Introducción'],['items','Contenido']]:[['title','Título'],['headline','Dato principal'],['body','Contenido']];$('#editorForm').innerHTML=fields.map(([k,l])=>k==='category'?`<div class="field"><label>${l}</label><select id="field-${k}"><option value="">Elegir categoría</option><option>Lugar</option><option>Patrimonio</option><option>Historia</option><option>Turismo</option><option>Cultura</option><option>Rural</option><option>Naturaleza</option><option>Producción</option></select></div>`:`<div class="field"><label>${l}</label>${['body','intro','items'].includes(k)?`<textarea id="field-${k}" placeholder="Podés dejar el texto de la plantilla o editarlo."></textarea>`:`<input id="field-${k}" placeholder="Podés dejar el texto de la plantilla o editarlo.">`}</div>`).join('');document.querySelectorAll('#editorForm input,#editorForm textarea,#editorForm select').forEach(el=>{const k=el.id.replace('field-','');el.value=state.data[k]??'';el.oninput=()=>{state.data[k]=el.value;renderPreview()}})}
function bodyHTML(){const d=state.data;if(state.type==='guide')return `<ul>${(d.items||'').split(/\r?\n/).filter(clean).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;return `<p>${esc(d.body||d.intro||d.headline||'')}</p>`}
function renderPreview(){const d=state.data,p=PHOTO_BANK.find(x=>x.id===state.photoId),tpl=TEMPLATES.find(t=>t.photo===state.photoId);const image=state.image?`<img src="${esc(state.image)}" alt="Fotografía real de San Patricio del Chañar">`:'';const meta=state.type==='ficha'&&d.category?`<div class="piece-meta">${esc(d.category)}${d.location?` · ${esc(d.location)}`:''}</div>`:'';const source=p?`<div class="piece-source">Imagen: ${esc(p.source)} · <a href="${p.url}" target="_blank">fuente</a></div>`:'';$('#canvasPreview').innerHTML=`<article class="piece ${state.type} style-${tpl?.style||'vino'}"><div class="piece-image">${image}<div class="image-overlay"></div><div class="photo-stamp">SAN PATRICIO DEL CHAÑAR</div></div><div class="piece-content"><div class="piece-kicker">OCARINA · CULTURA · TURISMO</div><h3>${esc(d.title||'Elegí una plantilla')}</h3>${d.subtitle?`<div class="piece-subtitle">${esc(d.subtitle)}</div>`:''}${d.headline?`<div class="piece-headline">${esc(d.headline)}</div>`:''}${meta}${bodyHTML()}${d.source?`<div class="piece-credit">Contenido: ${esc(d.source)}</div>`:''}${source}<div class="piece-brand">Fábrica Chañar · Historias, personas y territorio</div></div></article>`}
function validate(){const d=state.data;if(!clean(d.title)){status('Elegí una plantilla.');return false}const text=state.type==='guide'?clean(d.intro)||clean(d.items):clean(d.body)||clean(d.headline);if(!text){status('Falta contenido.');return false}return true}function save(){if(!validate())return;setLibrary([{id:'pieza-'+Date.now(),type:state.type,data:{...state.data},image:state.image,photoId:state.photoId,created:new Date().toISOString()},...library()]);status('Pieza guardada.')}
function openLibrary(){const a=library();$('#libraryList').innerHTML=a.length?a.map(x=>`<div class="library-card"><div><strong>${esc(x.data?.title||PRODUCTS[x.type]?.name)}</strong><small>${esc(PRODUCTS[x.type]?.name||x.type)} · ${new Date(x.created).toLocaleDateString('es-AR')}</small></div><div class="library-buttons"><button data-open="${x.id}">Abrir</button><button data-delete="${x.id}">Eliminar</button></div></div>`).join(''):'<p class="empty">Todavía no guardaste piezas.</p>';$('#libraryPanel').classList.remove('hidden');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const x=library().find(y=>y.id===b.dataset.open);if(!x)return;state={type:x.type,data:x.data||{},image:x.image||null,photoId:x.photoId||null};renderProducts();renderTemplates();renderForm();renderPreview();$('#libraryPanel').classList.add('hidden')});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{setLibrary(library().filter(x=>x.id!==b.dataset.delete));openLibrary()})}
async function exportImage(kind){if(!validate())return;if(typeof html2canvas!=='function'){status('No está disponible el exportador.');return}try{const canvas=await html2canvas($('#canvasPreview'),{scale:2,useCORS:true,allowTaint:false,backgroundColor:'#f4eee1'});const a=document.createElement('a');a.download=`fabrica-chanar-${Date.now()}.${kind}`;a.href=canvas.toDataURL(kind==='jpg'?'image/jpeg':'image/png',.94);a.click();status(`Descargada en ${kind.toUpperCase()}.`)}catch(e){status('La foto externa no permite exportación automática. Podés abrir la fuente o usar una foto propia.')}}
$('#btnGenerate').onclick=()=>{if(validate()){renderPreview();status('Generada. Descargala si te gusta.')}};$('#btnSave').onclick=save;$('#btnPng').onclick=()=>exportImage('png');$('#btnJpg').onclick=()=>exportImage('jpg');$('#btnPrint').onclick=()=>{if(validate())window.print()};$('#btnLibrary').onclick=openLibrary;$('#btnCloseLibrary').onclick=()=>$('#libraryPanel').classList.add('hidden');renderProducts();renderTemplates();renderForm();renderPreview();renderPhotoBank();updateLibraryCount();
