/* FÁBRICA CHAÑAR — NÚCLEO ÚNICO v14 · PRODUCCIÓN */
(function(){
  const PRODUCTS={
    postal:{icon:'▣',name:'Postal',desc:'Recuerdo visual, breve y coleccionable.',hint:'Imagen · emoción · dato',value:'Memoria e identidad en un objeto pequeño para guardar.',format:'10 × 15 cm'},
    ficha:{icon:'▤',name:'Ficha cultural',desc:'Pieza documental sobre un lugar o historia.',hint:'Contexto · categoría · lugar',value:'Una pequeña historia local convertida en documento.',format:'12 × 18 cm'},
    guide:{icon:'⌁',name:'Guía breve',desc:'Pieza útil para recorrer y descubrir.',hint:'Apertura · recorrido · hitos',value:'Información que sirve para mirar, recorrer y descubrir.',format:'15 × 21 cm'},
    infographic:{icon:'◈',name:'Infografía',desc:'Lámina para comprender una relación, proceso o dato.',hint:'Titular · dato · síntesis',value:'Una relación local que se entiende y se conserva.',format:'21 × 29,7 cm'}
  };
  const FORMATS={
    '10x15':{name:'Postal · 10 × 15 cm',size:'100 × 150 mm',ratio:'2/3'},
    '12x18':{name:'Ficha · 12 × 18 cm',size:'120 × 180 mm',ratio:'2/3'},
    '15x21':{name:'Guía · 15 × 21 cm',size:'150 × 210 mm',ratio:'5/7'},
    '21x29.7':{name:'Infografía · 21 × 29,7 cm',size:'210 × 297 mm',ratio:'210/297'},
    vertical:{name:'Digital vertical',size:'1080 × 1350',ratio:'4/5'},
    square:{name:'Cuadrada',size:'1200 × 1200',ratio:'1/1'},
    horizontal:{name:'Horizontal',size:'1600 × 1000',ratio:'8/5'},
    a5:{name:'A5 · 14,8 × 21 cm',size:'148 × 210 mm',ratio:'148/210'},
    a4:{name:'A4 · 21 × 29,7 cm',size:'210 × 297 mm',ratio:'210/297'}
  };
  let active='postal',format='auto';const $=s=>document.querySelector(s);
  function contract(id){return window.FabricaEngine?.contracts?.[id]||{identity:'pieza editorial',defaultFormat:'10x15',formats:['10x15']}}
  function law(id){return window.FabricaProductLaws?.get?.(id)||null}
  function productHTML(){return Object.entries(PRODUCTS).map(([id,p])=>{const c=contract(id),l=law(id),fmt=l?.format?.preferred||c.defaultFormat||p.format;return `<button class="central-product ${id===active?'is-active':''}" data-product="${id}" type="button" aria-pressed="${id===active}"><span class="central-product-icon">${p.icon}</span><span class="central-product-copy"><strong>${p.name}</strong><small>${p.desc}</small><em>${l?.value||p.value}</em><i>${p.format} · formato óptimo</i></span><span class="central-check">✓</span></button>`}).join('')}
  function formatOptions(){const allowed=contract(active).formats||Object.keys(FORMATS);return `<option value="auto">Automático · ${PRODUCTS[active].format}</option>${allowed.map(id=>{const f=FORMATS[id];return f?`<option value="${id}">${f.name}</option>`:''}).join('')}`}
  function render(){const controls=$('.controls');if(!controls)return;controls.querySelector('.central-shell')?.remove();const shell=document.createElement('section');shell.className='central-shell';shell.innerHTML=`<div class="central-intro"><span class="central-kicker">NÚCLEO ÚNICO DE PRODUCCIÓN</span><h2>¿Qué querés fabricar?</h2><p>Elegí una familia. La Fábrica resuelve curaduría, composición, texto, imagen, color, textura, dato, reverso, procedencia y salida según la razón de ser de cada producto.</p></div><div class="central-products">${productHTML()}</div><div class="central-selected" id="centralSelected"></div><div class="central-action-row"><button id="centralProduce" class="central-produce" type="button">✦ Fabricar ${PRODUCTS[active].name}</button><span id="centralStatus" class="central-mini">Cada familia conserva su escala física y su formato óptimo.</span></div><details class="central-options"><summary>⚙ Más opciones</summary><div class="central-option-grid"><label>Formato<select id="centralFormat">${formatOptions()}</select></label><div><span class="central-label">Dirección visual</span><div class="central-auto">Automática según producto + tema + imagen</div></div><div><span class="central-label">Escala</span><div class="central-auto">Postal pequeña → ficha compacta → guía media → infografía grande</div></div><div><span class="central-label">Salida</span><div class="central-auto">PNG · JPG · PDF / impresión</div></div></div></details>`;controls.prepend(shell);['#productGrid','#templateGrid','#editorForm','.actions','#collectionStudio','.step','#status','#masterProductsPanel','#collectionGrid'].forEach(sel=>controls.querySelectorAll(sel).forEach(el=>el.classList.add('central-legacy-hidden')));bind(shell);updateSelected(shell)}
  function updateSelected(shell){const el=shell?.querySelector('#centralSelected');if(!el)return;const c=contract(active),l=law(active),p=PRODUCTS[active];el.innerHTML=`<span class="central-selected-name">${p.name}</span><span class="central-selected-copy"><b>${l?.identity||c.identity||'pieza editorial'}</b><small>${l?.promise||c.layout||'Dirección editorial automática'} · ${p.format}</small></span>`}
  function setActive(id){if(!PRODUCTS[id])return;active=id;format='auto';document.querySelectorAll('.central-product').forEach(b=>{const on=b.dataset.product===id;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',String(on))});const b=$('#centralProduce');if(b)b.textContent='✦ Fabricar '+PRODUCTS[id].name;const select=$('#centralFormat');if(select)select.innerHTML=formatOptions();updateSelected(document.querySelector('.central-shell'))}
  async function waitForSelector(maxMs=2500){const started=Date.now();while((window.FabricaEngine?.materialSelectorVersion||0)<11){if(Date.now()-started>=maxMs)return false;await new Promise(r=>setTimeout(r,50))}return true}
  async function waitForCommit(product,maxMs=12000){const started=Date.now();while(Date.now()-started<maxMs){if(typeof state!=='undefined'&&state.factoryMeta?.closedCatalog?.[product]?.committed===true)return true;await new Promise(r=>setTimeout(r,50))}return false}
  async function produce(){const b=$('#centralProduce'),s=$('#centralStatus');if(b)b.disabled=true;if(s)s.textContent='La Fábrica está preparando la materia prima…';try{const selectorReady=await waitForSelector();if(!selectorReady){if(s)s.textContent='La curaduría todavía no está lista. No se fabricó una pieza incompleta.';return}if(s)s.textContent='La Fábrica está trabajando…';const allowed=contract(active).formats||[],requested=format==='auto'||!allowed.includes(format)?undefined:format;const result=await window.FabricaEngine?.produce?.({type:active,format:requested});if(result?.ok){const finalFormat=result.format||result.contract?.defaultFormat||requested||'10x15';if(typeof state!=='undefined'){state.centralProduct=active;state.centralFormat=finalFormat;state.factoryMeta={...(state.factoryMeta||{}),centralFormat:finalFormat}}document.getElementById('btnSave')?.click();const committed=await waitForCommit(active);if(!committed){if(s)s.textContent='La pieza quedó fabricada pero el guardado no confirmó la matriz. No se habilitó otra fabricación.';return}if(s)s.textContent=`Lista y guardada ✨ ${FORMATS[finalFormat]?.name||finalFormat}. Revisá, descargá o fabricá otra.`;if(window.matchMedia?.('(max-width:760px)').matches)document.querySelector('.preview-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}else if(s)s.textContent=result?.reason==='closed-catalog-exhausted'?'Esta familia ya consumió sus 10 matrices cerradas.':result?.reason==='production-busy'?'La Fábrica ya está fabricando otra pieza.':'No se pudo fabricar una pieza válida.'}catch(err){console.error(err);if(s)s.textContent='Hubo un problema. No se guardó una pieza incompleta.'}finally{if(b)b.disabled=false}}
  function bind(shell){shell.querySelectorAll('.central-product').forEach(b=>b.addEventListener('click',()=>setActive(b.dataset.product)));shell.querySelector('#centralProduce')?.addEventListener('click',produce);shell.querySelector('#centralFormat')?.addEventListener('change',e=>{format=e.target.value;if(typeof state!=='undefined')state.centralFormat=format})}
  function boot(){if(document.body.dataset.centralFactory)return;document.body.dataset.centralFactory='1';setTimeout(()=>{render();setTimeout(()=>window.renderPreview?.(),350)},350)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.FabricaCentral={version:14,products:PRODUCTS,formats:FORMATS,produce,setActive};
})();