(() => {
  const V6KEY='fabrica-chanar-v6-media';
  let v6={media:[],layers:[],sources:[],loaded:false};
  const q=s=>document.querySelector(s), esc6=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const save6=()=>localStorage.setItem(V6KEY,JSON.stringify(v6));
  const load6=()=>{try{const x=JSON.parse(localStorage.getItem(V6KEY)||'{}');v6={...v6,...x,media:Array.isArray(x.media)?x.media:[],layers:Array.isArray(x.layers)?x.layers:[],sources:Array.isArray(x.sources)?x.sources:[]};}catch{}};
  function shell(){
    const main=document.querySelector('main'); if(!main||document.querySelector('#v6Desk'))return;
    const sec=document.createElement('section'); sec.id='v6Desk'; sec.className='v6-section';
    sec.innerHTML=`<p class="eyebrow">v6.0 · BANCO MULTIMEDIA + FUENTES CHAÑAR</p><h2>Memoria con procedencia.</h2><p class="v5-muted">La fábrica ahora distingue dato, activo, fuente, licencia y geometría. Nada se vuelve reutilizable por estar publicado en internet.</p>
      <div class="v6-grid"><div class="v6-card"><span>Medios registrados</span><b id="v6MediaKpi">0</b></div><div class="v6-card"><span>Reutilizables</span><b id="v6OkKpi">0</b></div><div class="v6-card"><span>Referencias</span><b id="v6RefKpi">0</b></div><div class="v6-card"><span>Fuentes</span><b id="v6SourceKpi">0</b></div></div>
      <div class="v6-toolbar"><button class="v6-btn primary" id="v6Add">Registrar activo</button><button class="v6-btn" id="v6Export">Exportar manifiesto</button><button class="v6-btn" id="v6Reload">Recargar fuentes del repositorio</button></div>
      <div id="v6FormWrap" class="hidden"></div><div id="v6Audit"></div><div id="v6MediaTable"></div>`;
    main.insertBefore(sec,main.querySelector('.workspace'));
    q('#v6Add').onclick=()=>toggleForm(); q('#v6Export').onclick=exportManifest; q('#v6Reload').onclick=()=>loadRepositoryData(true);
    render6();
  }
  function toggleForm(){const w=q('#v6FormWrap'); if(!w)return; if(!w.innerHTML){w.innerHTML=`<div class="v6-form"><label>Nombre<input id="mName" placeholder="Ej. Foto del Dique Compensador"></label><label>Tipo<select id="mType"><option>foto</option><option>mapa</option><option>documento</option><option>audio</option><option>video</option></select></label><label>Autor / propietario<input id="mAuthor" placeholder="Persona, institución u Ocarina"></label><label>Estado<select id="mState"><option value="pendiente">pendiente</option><option value="reutilizable">reutilizable</option><option value="referencia">referencia</option></select></label><label>Licencia<input id="mLicense" placeholder="CC BY 4.0 / autorización / propia / desconocida"></label><label>URL de origen<input id="mUrl" placeholder="https://..."></label><label>¿Permite modificación?<select id="mMod"><option value="no">no verificado</option><option value="si">sí</option><option value="no">no</option></select></label><label>¿Permite uso comercial?<select id="mCommercial"><option value="no">no verificado</option><option value="si">sí</option><option value="no">no</option></select></label><label class="v6-full">Texto de atribución<input id="mCredit" placeholder="Crédito requerido por la licencia"></label><label class="v6-full">Notas<textarea id="mNotes" placeholder="Fecha de consulta, permiso, restricciones, vínculo con un registro, etc."></textarea></label></div><div class="v6-toolbar"><button class="v6-btn primary" id="mSave">Guardar activo</button><button class="v6-btn" id="mCancel">Cancelar</button></div>`;q('#mCancel').onclick=()=>{w.innerHTML='';};q('#mSave').onclick=saveMedia;} w.classList.toggle('hidden');}
  function saveMedia(){const item={id:`MED-${Date.now()}`,nombre:q('#mName').value.trim(),tipo:q('#mType').value,autor:q('#mAuthor').value.trim(),estado:q('#mState').value,licencia:q('#mLicense').value.trim(),url:q('#mUrl').value.trim(),modificacion:q('#mMod').value,comercial:q('#mCommercial').value,atribucion:q('#mCredit').value.trim(),notas:q('#mNotes').value.trim(),consultado:new Date().toISOString()}; if(!item.nombre){alert('El activo necesita un nombre.');return}v6.media.unshift(item);save6();q('#v6FormWrap').innerHTML='';render6();}
  function render6(){const ok=v6.media.filter(x=>x.estado==='reutilizable').length,ref=v6.media.filter(x=>x.estado==='referencia').length;q('#v6MediaKpi').textContent=v6.media.length;q('#v6OkKpi').textContent=ok;q('#v6RefKpi').textContent=ref;q('#v6SourceKpi').textContent=v6.sources.length;const audit=v6.media.filter(x=>x.estado==='reutilizable').every(x=>x.licencia&&x.url&&x.autor&&x.comercial==='si');q('#v6Audit').innerHTML=`<div class="v6-audit ${audit?'ok':'warn'}"><strong>Auditoría de reutilización:</strong> ${audit?'Los activos marcados reutilizables tienen licencia/origen/autor y permiso comercial registrados.':'Hay activos que todavía no tienen evidencia suficiente para uso comercial. La fábrica debe mantenerlos como referencia o pendiente hasta verificar.'}</div>`;q('#v6MediaTable').innerHTML=v6.media.length?`<div style="overflow:auto"><table class="v6-table"><thead><tr><th>ID</th><th>Activo</th><th>Derechos</th><th>Procedencia</th><th>Uso</th><th></th></tr></thead><tbody>${v6.media.map(x=>`<tr><td>${esc6(x.id)}</td><td><strong>${esc6(x.nombre)}</strong><div class="v6-small">${esc6(x.tipo)} · ${esc6(x.autor||'autor pendiente')}</div></td><td><span class="v6-pill ${x.estado==='reutilizable'?'ok':'warn'}">${esc6(x.estado)}</span><div class="v6-small">${esc6(x.licencia||'licencia pendiente')}</div></td><td>${x.url?`<a href="${esc6(x.url)}" target="_blank" rel="noopener">origen</a>`:'URL pendiente'}</td><td>${x.comercial==='si'?'comercial permitido':'no verificado'}</td><td><button class="v6-btn" data-del6="${esc6(x.id)}">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="v6-empty">Todavía no hay activos multimedia registrados. Usá “Registrar activo” para construir el banco con trazabilidad.</div>';
    q('#v6MediaTable').querySelectorAll('[data-del6]').forEach(b=>b.onclick=()=>{v6.media=v6.media.filter(x=>x.id!==b.dataset.del6);save6();render6();});
  }
  function exportManifest(){const blob=new Blob([JSON.stringify({version:'6.0.0',exported:new Date().toISOString(),media:v6.media,sources:v6.sources,layers:v6.layers},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fabrica-chanar-v6-manifiesto.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
  async function loadRepositoryData(show){try{const [core,src]=await Promise.all([fetch('data/chanar-core.json',{cache:'no-store'}).then(r=>r.json()),fetch('data/sources.json',{cache:'no-store'}).then(r=>r.json())]);const regs=core.registros||core.records||[];if(typeof memory==='object'&&Array.isArray(regs)){const ids=new Set(memory.records.map(x=>x.id));memory.records.push(...regs.filter(x=>!ids.has(x.id)));saveMemory();}v6.sources=Array.isArray(src)?src:(src.fuentes||src.sources||[]);save6();render6();if(show)alert(`Fuentes cargadas: ${v6.sources.length}. Registros base: ${regs.length}.`);}catch(e){if(show)alert('No se pudieron cargar automáticamente los datos del repositorio. La aplicación sigue funcionando con memoria local.');}}
  function boot(){load6();shell();loadRepositoryData(false);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
