(() => {
  const q=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const KEY='fabrica-chanar-v7-launch';
  const defaults={checks:{core:true,source:true,media:true,atlas:true,producer:true},lastRun:null};
  let launch={...defaults};
  try{launch={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}'),checks:{...defaults.checks,...(JSON.parse(localStorage.getItem(KEY)||'{}').checks||{})}}}catch{}
  const save=()=>localStorage.setItem(KEY,JSON.stringify(launch));
  function add(){const main=q('main');if(!main||q('#v7Launch'))return;const sec=document.createElement('section');sec.id='v7Launch';sec.className='v7-section';sec.innerHTML=`<p class="eyebrow">v7.0 · PUESTA EN MARCHA</p><h2>De laboratorio a fábrica operativa.</h2><p class="v5-muted">Esta capa ordena el salto final: comprobar el núcleo, preparar el despliegue, ejecutar una prueba de producción y dejar una ruta clara para trabajar todos los días.</p><div class="v7-grid"><div class="v7-card"><span>Versión</span><b>7.0</b></div><div class="v7-card"><span>Modo</span><b>Producción</b></div><div class="v7-card"><span>Checks</span><b id="v7Checks">0/5</b></div><div class="v7-card"><span>Último control</span><b id="v7Last">—</b></div></div><div class="v7-flow"><div class="v7-step">1 · Datos</div><div class="v7-step">2 · Fuentes</div><div class="v7-step">3 · Derechos</div><div class="v7-step">4 · Atlas</div><div class="v7-step">5 · Producto</div><div class="v7-step">6 · Despliegue</div></div><div class="v7-checks">${[['core','Núcleo territorial','chanar-core.json + registros'],['source','Fuentes','fuentes institucionales registradas'],['media','Derechos','banco multimedia auditado'],['atlas','Atlas','GeoJSON solo documentado'],['producer','Fabricación','postal/ficha/guía/exportación']].map(([id,t,d])=>`<label class="v7-check"><input type="checkbox" data-v7="${id}" ${launch.checks[id]?'checked':''}> <strong>${t}</strong><br><span class="v7-small">${d}</span></label>`).join('')}</div><div class="v7-toolbar"><button class="v7-btn primary" id="v7Run">Ejecutar control de puesta en marcha</button><button class="v7-btn" id="v7Reset">Restablecer checklist</button><a class="v7-btn" href="https://github.com/eliasmartinezcultural-glitch/fabrica-chanar" target="_blank" rel="noopener">Repositorio</a></div><div id="v7Status" class="v7-status">Listo para controlar.</div>`;main.insertBefore(sec,main.querySelector('.workspace'));sec.querySelectorAll('[data-v7]').forEach(x=>x.onchange=()=>{launch.checks[x.dataset.v7]=x.checked;save();render()});q('#v7Run').onclick=run;q('#v7Reset').onclick=()=>{launch={...defaults,checks:{...defaults.checks}};save();render()};render()}
  async function run(){const tests=[];const paths=['data/chanar-core.json','data/sources.json','data/media-manifest.json','data/map-layers.json'];for(const p of paths){try{const r=await fetch(p,{cache:'no-store'});tests.push([p,r.ok])}catch{tests.push([p,false])}}const core=tests.find(x=>x[0].includes('chanar-core'))?.[1],src=tests.find(x=>x[0].includes('sources'))?.[1],media=tests.find(x=>x[0].includes('media'))?.[1],atlas=tests.find(x=>x[0].includes('map-layers'))?.[1],producer=typeof window.html2canvas==='function';launch.lastRun=new Date().toISOString();launch.checks={core:!!core,source:!!src,media:!!media,atlas:!!atlas,producer};save();render();q('#v7Status').className='v7-status '+(Object.values(launch.checks).every(Boolean)?'ok':'warn');q('#v7Status').innerHTML=Object.values(launch.checks).every(Boolean)?'<strong>APTO PARA TRABAJAR.</strong> Núcleo, fuentes, manifiestos, Atlas y motor de exportación están disponibles.':'<strong>HAY BLOQUEOS.</strong> Revisá los módulos marcados antes de considerar la fábrica operativa.'}
  function render(){const n=Object.values(launch.checks).filter(Boolean).length;q('#v7Checks').textContent=`${n}/5`;q('#v7Last').textContent=launch.lastRun?new Date(launch.lastRun).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}):'—';q('#v7Launch').querySelectorAll('[data-v7]').forEach(x=>x.checked=!!launch.checks[x.dataset.v7])}
  function boot(){add()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();