(()=>{
const KEY9='fabrica-chanar-v9-orders';
const q9=s=>document.querySelector(s);const e9=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
let orders9=[];let selected9=null;
const statuses9=[['idea','Idea'],['investigacion','Investigación'],['lista','Lista para producir'],['produccion','En producción'],['terminada','Terminada']];
function load9(){try{orders9=JSON.parse(localStorage.getItem(KEY9)||'[]');if(!Array.isArray(orders9))orders9=[]}catch{orders9=[]}}
function save9(){localStorage.setItem(KEY9,JSON.stringify(orders9));render9()}
function inject9(){if(q9('#v9Production'))return;const main=document.querySelector('.app-shell'),anchor=q9('#v8Production')||document.querySelector('.workspace');if(!main||!anchor)return;const s=document.createElement('section');s.id='v9Production';s.className='v9-panel';main.insertBefore(s,anchor.nextSibling)}
function render9(){const host=q9('#v9Production');if(!host)return;const counts=Object.fromEntries(statuses9.map(x=>[x[0],orders9.filter(o=>o.status===x[0]).length]));host.innerHTML=`<div class="v9-head"><div><div class="v9-eyebrow">v9.0 · OPERACIÓN PRODUCTIVA</div><h2>Órdenes reales, no solo piezas</h2><p class="v9-sub">La fábrica ahora puede transformar una idea o registro en una orden de trabajo con cliente/proyecto, productos, estado, control y manifiesto. Todo queda local en el navegador.</p></div><div class="v9-kpis">${statuses9.slice(0,4).map(x=>`<div class="v9-kpi"><span>${x[1]}</span><b>${counts[x[0]]}</b></div>`).join('')}</div></div><div class="v9-statuses">${statuses9.map(x=>`<div class="v9-status ${selected9?.status===x[0]?'active':''}">${x[1]} · ${counts[x[0]]}</div>`).join('')}</div><div class="v9-grid"><div class="v9-card"><strong>Nueva orden</strong><div class="v9-fields"><label>Nombre de orden<input id="v9Name" placeholder="Ej. Colección Dique Compensador"></label><label>Cliente / destinatario<input id="v9Client" placeholder="Particular, comercio, institución o interno"></label><label>Proyecto<input id="v9Project" placeholder="Proyecto relacionado"></label><label>Registro territorial<input id="v9Record" placeholder="ID del registro, si corresponde"></label><label>Objetivo<textarea id="v9Goal" placeholder="Qué hay que producir y para qué"></textarea></label></div><strong>Productos</strong><div class="v9-products"><label><input type="checkbox" value="ficha" checked> Ficha</label><label><input type="checkbox" value="postal" checked> Postal</label><label><input type="checkbox" value="guide"> Guía</label><label><input type="checkbox" value="infographic"> Infografía</label><label><input type="checkbox" value="map"> Mapa</label></div><div class="v9-actions"><button class="v9-btn" id="v9Create">Crear orden</button><button class="v9-btn alt" id="v9FromSelected">Usar registro seleccionado</button></div><p class="v9-note">No se crea una afirmación comercial ni un precio automáticamente. La orden organiza el trabajo.</p></div><div class="v9-card"><strong>Tablero de producción</strong><div class="v9-orders">${orders9.length?orders9.map(o=>`<div class="v9-order"><strong>${e9(o.name)}</strong><small>${e9(o.client||'Interno')} · ${e9(o.statusLabel)} · ${e9(o.recordId||'sin registro')}</small><p class="v9-note">${e9(o.products.join(' · '))}</p><div class="v9-progress"><i style="width:${o.progress}%"></i></div><div class="v9-actions"><button class="v9-btn" data-open9="${e9(o.id)}">Abrir</button><button class="v9-btn alt" data-export9="${e9(o.id)}">Manifiesto</button></div></div>`).join(''):'<p class="v9-note">Todavía no hay órdenes. La primera debería salir de un registro documentado y una foto propia de Ocarina.</p>'}</div></div></div>`;
q9('#v9Create').onclick=create9;q9('#v9FromSelected').onclick=fromSelected9;host.querySelectorAll('[data-open9]').forEach(b=>b.onclick=()=>open9(b.dataset.open9));host.querySelectorAll('[data-export9]').forEach(b=>b.onclick=()=>export9(b.dataset.export9));}
function selectedRecord9(){return window.v8?.selected||null}
function fromSelected9(){const r=selectedRecord9();if(!r){alert('Primero seleccioná un registro en la línea de producción v8.');return}q9('#v9Name').value=`Colección · ${r.nombre||r.id}`;q9('#v9Record').value=r.id||'';q9('#v9Goal').value=r.resumen||'';}
function create9(){const name=q9('#v9Name').value.trim();if(!name){alert('Poné un nombre para la orden.');return}const products=[...document.querySelectorAll('#v9Production .v9-products input:checked')].map(x=>x.value);const r={id:`ORD-${Date.now()}`,name,client:q9('#v9Client').value.trim(),project:q9('#v9Project').value.trim(),recordId:q9('#v9Record').value.trim(),goal:q9('#v9Goal').value.trim(),products:products.length?products:['ficha'],status:'idea',statusLabel:'Idea',progress:0,rights:'pendiente_de_verificacion',created:new Date().toISOString(),updated:new Date().toISOString()};orders9.unshift(r);selected9=r;save9()}
function open9(id){const o=orders9.find(x=>x.id===id);if(!o)return;selected9=o;const idx=statuses9.findIndex(x=>x[0]===o.status);const next=statuses9[Math.min(idx+1,statuses9.length-1)];if(idx<statuses9.length-1&&confirm(`Orden: ${o.name}\n\nEstado actual: ${o.statusLabel}\n\n¿Avanzar a ${next[1]}?`)){o.status=next[0];o.statusLabel=next[1];o.progress=Math.round((statuses9.findIndex(x=>x[0]===o.status)/(statuses9.length-1))*100);o.updated=new Date().toISOString();save9()}}
function export9(id){const o=orders9.find(x=>x.id===id);if(!o)return;const manifest={version:'9.0.0',tipo:'orden_produccion',orden:o,regla:'Los derechos de cada activo deben verificarse antes de exportación o uso comercial.',fuente_de_contenido:o.recordId?'registro territorial':'carga manual',estado:'control interno'};const blob=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${o.id}.json`;a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('DOMContentLoaded',()=>{load9();inject9();render9()});window.addEventListener('fabrica:v9-refresh',render9);window.v9={refresh:render9,getOrders:()=>orders9};
})();